/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
    colors: {
      black: "#181818",
      main: "#f5f5f5",
      menu: "#FFFFFF",
      "menu-hover": "#FDEBEF",
      normal: "#8D8D8D",
      earth: " #F2A837",
      fire: "#F57039",
      wind: "#94C8FD",
      venom: "#9537C6",
      mud: "#AF7B2D",
      beetle: "#B9C33F",
      ghost: "#81447C",
      iron: "#71AAD2",
      water: "#2D94F2",
      grass: "#4ED02E",
      electric: "#FECF08",
      ice: "#4EDDFE",
      dragon: "#424BD5",
      dark: "#4D4346",
      fairy: "#ED8BE5",
      primary: "#E9395E",
    },
  },
};
